### ISSUE TITLE
[Feature Request?] Integrate with Code Actions

### ISSUE THREAD

**Issue by EricDriussi** [CKolkey/ts-node-action#10]
Hi there! loving the plugin, really cool work!

I think it might be cool to integrate the node-actions into the lsp code actions.

So if my cursor is on top of a `bool` and I run `vim.lsp.buf.code_action()`, the output would also list "Toggle Boolean" as an option.

I have no idea if that is possible nor how to do it, I just though I'd leave the idea hanging ^^

**Comment by CKolkey** [comment]
Its a cool idea - and seems to have some support at least. The biggest hurdle here is that all functions are currently anonymous, and I'd need to change up the API a fair bit to get it to list the _specific_ function that would be applied, and the name of the function. 

That said, I also don't use null-ls, or code-actions generally, so I'm probably not going to work on this. Feel free to open a PR though :)

**Comment by CKolkey** [comment]
Closed by #18
