### ISSUE TITLE
Bug: Splitting inserts spaces, even if you have set `noexpandtab`

### ISSUE THREAD

**Issue by chrisgrieser** [CKolkey/ts-node-action#2]
![2023-01-07 13 50 53](https://user-images.githubusercontent.com/73286100/211151497-c559d4fd-2811-4736-b357-a450da20cf80.gif)

**Comment by CKolkey** [comment]
Oh, right, I forgot some people use tabs. I'll see about updating the helper functions to respect that.

**Comment by CKolkey** [comment]
Should be fixed here: https://github.com/CKolkey/ts-node-action/commit/6f47679fbf85eace28f80d642926dd3f2e9f11dd

Feel free to reopen this issue if thats not the case.
