### ISSUE TITLE
Not enabled on tsx file by default? Is this a bug?

### ISSUE THREAD

**Issue by ariel-frischer** [CKolkey/ts-node-action#57]
Curious why did I have to add the `tsx = ` line to my `setup` function?

```
local ts_node_action = require("ts-node-action")
...
ts_node_action.setup({
    tsx = ts_node_action.node_actions.typescriptreact,
})
```
I would assume default node actions would just work but they were not enabled until I added this.

**Comment by CKolkey** [comment]
No, not a bug. This plugin is a framework for people to write their own functional transformations. I just bundle a handful that I've written, or have been contributed. 

I also don't do javáscript, so, feel free to open a PR :)
