### ISSUE TITLE
Suggest: apply = on multiline actions

### ISSUE THREAD

**Issue by unphased** [CKolkey/ts-node-action#60]
I noticed for split actions the new lines are not indented properly. I think this can be addressed by applying `=` reflow on all multiline replacements? Won't that work? 

Great plugin concept by the way. It's extremely powerful and helps showcase what treesitter can really do.

Separately from this I'm hoping to contribute a toggle action for js/ts to convert a template string expression into regular strings and vice versa. Something you couldn't dare attempt with regexes!

**Comment by unphased** [comment]
OK i found that there is a `format` option so for some reason it maybe isnt working or not set for the lua expansion... still looking up where the default action definition is...

**Comment by CKolkey** [comment]
I love being a rubber duck :)
